language: "ruby"

rvm:
  - "2.3.0"
  - "2.6.0"

sudo: false

install:
  - bundle install --retry=3

script:
  - bundle exec rspec

addons:
  code_climate:
    repo_token: dbc54b06cc8429eece856224982b7c177e3133a7a2c1218e28223725e5f968f0

after_success:
  - bundle exec codeclimate-test-reporter
